import { useEffect,useMemo,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import Layout from '../components/Layout';
import Loading from '../components/Loading';
import { createBacklink,deleteBacklink,updateBacklink,getBacklinks,getBacklinkOpportunities,createBacklinkOpportunity } from '../api/seoPlatformApi';
const fmt=(n)=>new Intl.NumberFormat('en-IN').format(Number(n||0));
const blank={source_url:'',target_url:'',anchor_text:'',domain_authority:'',status:'new',first_seen_at:'',last_seen_at:''};
export default function BacklinkIntelligence(){
 const {projectId}=useParams();const [data,setData]=useState(null);const [opps,setOpps]=useState([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [search,setSearch]=useState('');const [status,setStatus]=useState('all');const [edit,setEdit]=useState(null);const [opp,setOpp]=useState({referring_domain:'',source_url:'',target_url:'',anchor_text:'',authority:'',priority:'medium',notes:''});
 async function load(){try{setLoading(true);setError('');const b=await getBacklinks(projectId);setData(b);try{const o=await getBacklinkOpportunities(projectId);setOpps(o.opportunities||[])}catch(e){console.error('Load backlink opportunities error:',e);setOpps([])}}catch(e){setError(e.response?.data?.message||e.message||'Unable to load backlinks')}finally{setLoading(false)}}
 useEffect(()=>{if(projectId)load()},[projectId]);
 const list=data?.backlinks||[];const active=list.filter(x=>x.status==='active').length;const lost=list.filter(x=>x.status==='lost').length;const fresh=list.filter(x=>x.status==='new').length;const domains=new Set(list.map(x=>{try{return new URL(x.source_url).hostname.toLowerCase()}catch{return String(x.source_url||'').toLowerCase()}})).size;
 const rows=useMemo(()=>{let r=status==='all'?list:list.filter(x=>x.status===status);if(search.trim()){const q=search.toLowerCase();r=r.filter(x=>[x.source_url,x.target_url,x.anchor_text].some(v=>String(v||'').toLowerCase().includes(q)))}return r},[list,status,search]);
 async function add(e){e.preventDefault();if(!edit?.source_url.trim())return;try{setSaving(true);const payload={...edit,domain_authority:edit.domain_authority===''?null:Number(edit.domain_authority)};if(edit.id)await updateBacklink(edit.id,payload);else await createBacklink(projectId,payload);setEdit(null);await load()}catch(e){setError(e.response?.data?.message||e.message)}finally{setSaving(false)}}
 async function remove(id){if(!confirm('Delete this backlink?'))return;try{await deleteBacklink(id);await load()}catch(e){setError(e.response?.data?.message||e.message)}}
 async function saveOpp(e){e.preventDefault();if(!opp.referring_domain.trim())return;try{await createBacklinkOpportunity(projectId,{...opp,authority:opp.authority===''?null:Number(opp.authority)});setOpp({referring_domain:'',source_url:'',target_url:'',anchor_text:'',authority:'',priority:'medium',notes:''});await load()}catch(e){setError(e.response?.data?.message||e.message)}}
 if(loading)return <Layout><Loading text="Loading backlink intelligence..."/></Layout>;
 return <Layout><header className="page-header"><div><small>SEO INTELLIGENCE</small><h1>Backlink Intelligence</h1><p>Project #{projectId} · {fmt(list.length)} tracked backlinks</p></div><div className="header-actions"><Link className="secondary" to={`/projects/${projectId}/seo`}>← SEO Command Center</Link><Link className="secondary" to={`/projects/${projectId}/seo/keywords`}>Keywords</Link><Link className="secondary" to={`/projects/${projectId}/seo/competitors`}>Competitors</Link></div></header>
 {error&&<div className="alert">{error}</div>}
 <div className="stats"><div className="stat-card"><small>Tracked Backlinks</small><strong>{fmt(list.length)}</strong><span>Full link inventory</span></div><div className="stat-card"><small>Active Backlinks</small><strong>{fmt(active)}</strong><span>Currently active</span></div><div className="stat-card"><small>Lost Backlinks</small><strong>{fmt(lost)}</strong><span>Recovery candidates</span></div><div className="stat-card"><small>Referring Domains</small><strong>{fmt(domains)}</strong><span>Unique source domains</span></div></div>
 <section className="panel"><div className="panel-title"><div><small>LINK INVENTORY</small><h2>{edit?.id?'Edit backlink':'Add backlink'}</h2></div></div><form className="intel-form" onSubmit={add}><input required value={edit?.source_url||''} onChange={e=>setEdit({...edit,source_url:e.target.value})} placeholder="Source URL *"/><input value={edit?.target_url||''} onChange={e=>setEdit({...edit,target_url:e.target.value})} placeholder="Target URL"/><input value={edit?.anchor_text||''} onChange={e=>setEdit({...edit,anchor_text:e.target.value})} placeholder="Anchor text"/><input type="number" min="0" max="100" step="0.1" value={edit?.domain_authority||''} onChange={e=>setEdit({...edit,domain_authority:e.target.value})} placeholder="Authority"/><select value={edit?.status||'new'} onChange={e=>setEdit({...edit,status:e.target.value})}><option value="new">New</option><option value="active">Active</option><option value="lost">Lost</option></select><input type="date" value={edit?.first_seen_at||''} onChange={e=>setEdit({...edit,first_seen_at:e.target.value})}/><input type="date" value={edit?.last_seen_at||''} onChange={e=>setEdit({...edit,last_seen_at:e.target.value})}/><button className="primary" disabled={saving}>{saving?'Saving...':edit?.id?'Update backlink':'Add backlink'}</button>{edit&&<button type="button" className="secondary-button" onClick={()=>setEdit(null)}>Clear</button>}</form></section>
 <section className="panel"><div className="panel-title"><div><small>BACKLINK PROFILE</small><h2>Source links</h2></div><span className="muted">{fmt(fresh)} new</span></div><div className="backlink-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search source, target or anchor..."/><div className="filter-tabs"><button className={`filter-tab ${status==='all'?'active':''}`} onClick={()=>setStatus('all')}>All</button><button className={`filter-tab ${status==='active'?'active':''}`} onClick={()=>setStatus('active')}>Active</button><button className={`filter-tab ${status==='lost'?'active':''}`} onClick={()=>setStatus('lost')}>Lost</button><button className={`filter-tab ${status==='new'?'active':''}`} onClick={()=>setStatus('new')}>New</button></div></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>Source</th><th>Target</th><th>Anchor</th><th>Authority</th><th>Status</th><th>First seen</th><th>Last seen</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><a href={r.source_url} target="_blank" rel="noreferrer"><b>{r.source_url}</b></a></td><td>{r.target_url||'—'}</td><td>{r.anchor_text||'—'}</td><td>{r.domain_authority==null?'—':Number(r.domain_authority).toFixed(1)}</td><td>{r.status}</td><td>{r.first_seen_at?new Date(r.first_seen_at).toLocaleDateString('en-IN'):'—'}</td><td>{r.last_seen_at?new Date(r.last_seen_at).toLocaleDateString('en-IN'):'—'}</td><td><button className="secondary-button" onClick={()=>setEdit({...blank,...r,first_seen_at:r.first_seen_at?.slice(0,10)||'',last_seen_at:r.last_seen_at?.slice(0,10)||''})}>Edit</button> <button className="danger-link" onClick={()=>remove(r.id)}>Delete</button></td></tr>)}</tbody></table></div>:<div className="empty-state">No backlinks match the current filter.</div>}</section>
 <section className="panel"><div className="panel-title"><div><small>LINK BUILDING</small><h2>Backlink opportunities</h2></div><span>{fmt(opps.length)} opportunities</span></div><form className="intel-form" onSubmit={saveOpp}><input required value={opp.referring_domain} onChange={e=>setOpp({...opp,referring_domain:e.target.value})} placeholder="Referring domain *"/><input value={opp.source_url} onChange={e=>setOpp({...opp,source_url:e.target.value})} placeholder="Source URL"/><input value={opp.target_url} onChange={e=>setOpp({...opp,target_url:e.target.value})} placeholder="Target URL"/><input value={opp.anchor_text} onChange={e=>setOpp({...opp,anchor_text:e.target.value})} placeholder="Anchor text"/><input type="number" min="0" max="100" step="0.1" value={opp.authority} onChange={e=>setOpp({...opp,authority:e.target.value})} placeholder="Authority"/><select value={opp.priority} onChange={e=>setOpp({...opp,priority:e.target.value})}><option>low</option><option>medium</option><option>high</option><option>critical</option></select><button className="primary">Save opportunity</button></form>{opps.length?<div className="table-wrap"><table><thead><tr><th>Domain</th><th>Source</th><th>Anchor</th><th>Authority</th><th>Type</th><th>Priority</th><th>Status</th></tr></thead><tbody>{opps.map((o,i)=><tr key={`${o.referring_domain}-${o.id||i}`}><td><b>{o.referring_domain}</b></td><td>{o.source_url||'—'}</td><td>{o.anchor_text||'—'}</td><td>{o.authority==null?'—':Number(o.authority).toFixed(1)}</td><td>{o.opportunity_type}</td><td>{o.priority}</td><td>{o.status}</td></tr>)}</tbody></table></div>:<div className="empty-state">No backlink opportunities yet. Competitor Intelligence can generate opportunities from observed competitor sources.</div>}</section>
 </Layout>
}
