import { useEffect,useMemo,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import Layout from '../components/Layout';
import Loading from '../components/Loading';
import { getCompetitorIntelligence,createCompetitor,deleteCompetitor,createCompetitorKeyword,deleteCompetitorKeyword,createCompetitorBacklink,deleteCompetitorBacklink,createBacklinkOpportunity,updateBacklinkOpportunity,deleteBacklinkOpportunity } from '../api/seoPlatformApi';

const n=(v)=>new Intl.NumberFormat('en-IN').format(Number(v||0));
const pos=(v)=>v==null?'—':Number(v).toFixed(1);

export default function CompetitorIntelligence(){
 const {projectId}=useParams(); const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [tab,setTab]=useState('overview'); const [search,setSearch]=useState('');
 const [domain,setDomain]=useState('');
 const [kw,setKw]=useState({competitorId:'',keyword:'',ranking_position:'',search_volume:'',ranking_url:'',traffic_estimate:'',difficulty:''});
 const [bl,setBl]=useState({competitorId:'',source_url:'',target_url:'',anchor_text:'',domain_authority:'',status:'active'});
 const [opp,setOpp]=useState({referring_domain:'',source_url:'',target_url:'',anchor_text:'',authority:'',priority:'medium',notes:''});
 async function load(){try{setLoading(true);setError('');setData(await getCompetitorIntelligence(projectId));}catch(e){setError(e.response?.data?.message||e.message||'Unable to load competitor intelligence')}finally{setLoading(false)}}
 useEffect(()=>{if(projectId){load();}},[projectId]);
 const competitors=data?.competitors||[], keywords=data?.keywords||[], backlinks=data?.backlinks||[], gaps=data?.keywordGaps||[], opportunities=data?.backlinkOpportunities||[], competitorSummary=data?.competitorSummary||[];
 const filteredKw=useMemo(()=>{const q=search.trim().toLowerCase();return !q?keywords:keywords.filter(x=>[x.keyword,x.competitor_domain,x.ranking_url].some(v=>String(v||'').toLowerCase().includes(q)))},[keywords,search]);
 const filteredBl=useMemo(()=>{const q=search.trim().toLowerCase();return !q?backlinks:backlinks.filter(x=>[x.source_url,x.target_url,x.anchor_text,x.competitor_domain].some(v=>String(v||'').toLowerCase().includes(q)))},[backlinks,search]);
 async function addCompetitor(e){e.preventDefault();if(!domain.trim())return;try{setSaving(true);await createCompetitor(projectId,{competitor_domain:domain.trim()});setDomain('');await load()}catch(e){setError(e.response?.data?.message||e.message)}finally{setSaving(false)}}
 async function addKw(e){e.preventDefault();if(!kw.competitorId||!kw.keyword.trim())return;try{setSaving(true);await createCompetitorKeyword(kw.competitorId,{...kw,ranking_position:kw.ranking_position===''?null:Number(kw.ranking_position),search_volume:kw.search_volume===''?null:Number(kw.search_volume),traffic_estimate:kw.traffic_estimate===''?null:Number(kw.traffic_estimate),difficulty:kw.difficulty===''?null:Number(kw.difficulty)});setKw({...kw,keyword:'',ranking_position:'',search_volume:'',ranking_url:'',traffic_estimate:'',difficulty:''});await load()}catch(e){setError(e.response?.data?.message||e.message)}finally{setSaving(false)}}
 async function addBl(e){e.preventDefault();if(!bl.competitorId||!bl.source_url.trim())return;try{setSaving(true);await createCompetitorBacklink(bl.competitorId,{...bl,domain_authority:bl.domain_authority===''?null:Number(bl.domain_authority)});setBl({...bl,source_url:'',target_url:'',anchor_text:'',domain_authority:''});await load()}catch(e){setError(e.response?.data?.message||e.message)}finally{setSaving(false)}}
 async function saveOpp(o){try{await createBacklinkOpportunity(projectId,o);await load()}catch(e){setError(e.response?.data?.message||e.message)}}

 if(loading)return <Layout><Loading text="Loading competitor intelligence..."/></Layout>;
 const s=data?.summary||{};
 return <Layout><header className="page-header"><div><small>SEO INTELLIGENCE</small><h1>Competitor Intelligence</h1><p>{data?.project?.website_url}</p></div><div className="header-actions"><Link className="secondary" to={`/projects/${projectId}/seo`}>← SEO Command Center</Link><Link className="secondary" to={`/projects/${projectId}/seo/keywords`}>Keywords</Link><Link className="secondary" to={`/projects/${projectId}/seo/backlinks`}>Backlinks</Link></div></header>
 {error&&<div className="alert">{error}</div>}

 <div className="stats"><div className="stat-card"><small>Competitors</small><strong>{n(s.competitors)}</strong><span>Tracked domains</span></div><div className="stat-card"><small>Competitor Keywords</small><strong>{n(s.competitorKeywords)}</strong><span>Tracked ranking terms</span></div><div className="stat-card"><small>Competitor Backlinks</small><strong>{n(s.competitorBacklinks)}</strong><span>Observed links</span></div><div className="stat-card"><small>Keyword Gaps</small><strong>{n(s.keywordGaps)}</strong><span>Not tracked by you</span></div></div>
 <section className="panel"><div className="panel-title"><div><small>COMPETITOR TRACKING</small><h2>Add competitor</h2></div></div><form className="inline-form" onSubmit={addCompetitor}><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="competitor.com"/><button className="primary" disabled={saving}>{saving?'Adding...':'Add competitor'}</button></form>{competitors.length>0&&<div className="competitor-chips">{competitors.map(c=><div className="competitor-chip" key={c.id}><b>{c.competitor_domain}</b><span>{n(c.keyword_count)} keywords · {n(c.active_backlink_count)} active backlinks · {n(c.backlink_count)} total links</span><button className="danger-link" onClick={async()=>{if(confirm('Delete competitor and all its tracked observations?')){try{await deleteCompetitor(c.id);await load()}catch(e){setError(e.response?.data?.message||e.message)}}}}>Delete</button></div>)}</div>}</section>
 <div className="filter-tabs"><button className={`filter-tab ${tab==='overview'?'active':''}`} onClick={()=>setTab('overview')}>Overview</button><button className={`filter-tab ${tab==='keywords'?'active':''}`} onClick={()=>setTab('keywords')}>Competitor Keywords</button><button className={`filter-tab ${tab==='backlinks'?'active':''}`} onClick={()=>setTab('backlinks')}>Competitor Backlinks</button><button className={`filter-tab ${tab==='opportunities'?'active':''}`} onClick={()=>setTab('opportunities')}>Backlink Opportunities</button><button className={`filter-tab ${tab==='tools'?'active':''}`} onClick={()=>setTab('tools')}>Free Research Tools</button></div>
 {tab==='overview'&&<><section className="panel"><div className="panel-title"><div><small>COMPETITOR COMPARISON</small><h2>Tracked competitor profile</h2></div><span>{n(competitorSummary.length)} domains</span></div>{competitorSummary.length?<div className="table-wrap"><table><thead><tr><th>Competitor</th><th>Keywords</th><th>Total backlinks</th><th>Active backlinks</th></tr></thead><tbody>{competitorSummary.map(c=><tr key={c.id}><td><b>{c.domain}</b></td><td>{n(c.keywords)}</td><td>{n(c.backlinks)}</td><td>{n(c.activeBacklinks)}</td></tr>)}</tbody></table></div>:<div className="empty-state">Add at least one competitor to start the comparison layer.</div>}</section><div className="grid"><section className="panel"><div className="panel-title"><div><small>KEYWORD GAP</small><h2>Competitor keywords you don't track</h2></div><span>{n(gaps.length)}</span></div>{gaps.length===0?<div className="empty-state">No competitor keyword gaps yet. Add competitor keyword data to discover opportunities.</div>:<div className="table-wrap"><table><thead><tr><th>Keyword</th><th>Competitor</th><th>Position</th><th>Volume</th></tr></thead><tbody>{gaps.slice(0,12).map(x=><tr key={`${x.competitor_domain}-${x.id}`}><td><b>{x.keyword}</b></td><td>{x.competitor_domain}</td><td>{pos(x.ranking_position)}</td><td>{n(x.search_volume)}</td></tr>)}</tbody></table></div>}</section><section className="panel"><div className="panel-title"><div><small>LINK GAP</small><h2>Potential backlink sources</h2></div><span>{n(opportunities.length)}</span></div>{opportunities.length===0?<div className="empty-state">No backlink opportunities yet.</div>:<div className="simple-list">{opportunities.slice(0,8).map((o,i)=><div className="opportunity-row" key={`${o.referring_domain}-${i}`}><div><b>{o.referring_domain}</b><span>{o.source_url||'Competitor referring source'}</span></div><div><span>{o.authority==null?'—':Number(o.authority).toFixed(1)} authority</span>{!o.id&&<button className="secondary-button" onClick={()=>saveOpp(o)}>Save</button>}</div></div>)}</div>}</section></div></>}
 {tab==='keywords'&&<><section className="panel"><div className="panel-title"><div><small>COMPETITOR KEYWORDS</small><h2>Add ranking observation</h2></div></div><form className="intel-form" onSubmit={addKw}><select value={kw.competitorId} onChange={e=>setKw({...kw,competitorId:e.target.value})}><option value="">Select competitor</option>{competitors.map(c=><option key={c.id} value={c.id}>{c.competitor_domain}</option>)}</select><input value={kw.keyword} onChange={e=>setKw({...kw,keyword:e.target.value})} placeholder="Keyword *"/><input type="number" value={kw.ranking_position} onChange={e=>setKw({...kw,ranking_position:e.target.value})} placeholder="Position"/><input type="number" value={kw.search_volume} onChange={e=>setKw({...kw,search_volume:e.target.value})} placeholder="Search volume"/><input value={kw.ranking_url} onChange={e=>setKw({...kw,ranking_url:e.target.value})} placeholder="Ranking URL"/><button className="primary" disabled={saving}>Save</button></form></section><section className="panel"><div className="panel-title"><div><small>RANKING INVENTORY</small><h2>Competitor keywords</h2></div><input className="compact-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..."/></div>{filteredKw.length?<div className="table-wrap"><table><thead><tr><th>Keyword</th><th>Competitor</th><th>Position</th><th>Volume</th><th>Traffic</th><th>Source</th><th>URL</th><th>Action</th></tr></thead><tbody>{filteredKw.map(x=><tr key={x.id}><td><b>{x.keyword}</b></td><td>{x.competitor_domain}</td><td>{pos(x.ranking_position)}</td><td>{n(x.search_volume)}</td><td>{n(x.traffic_estimate)}</td><td>{x.source||'manual'}</td><td>{x.ranking_url||'—'}</td><td><button className="danger-link" onClick={async()=>{if(confirm('Delete this keyword observation?')){try{await deleteCompetitorKeyword(x.competitor_id,x.id);await load()}catch(e){setError(e.response?.data?.message||e.message)}}}}>Delete</button></td></tr>)}</tbody></table></div>:<div className="empty-state">No competitor keyword observations.</div>}</section></>}
 {tab==='backlinks'&&<><section className="panel"><div className="panel-title"><div><small>COMPETITOR BACKLINKS</small><h2>Add observed backlink</h2></div></div><form className="intel-form" onSubmit={addBl}><select value={bl.competitorId} onChange={e=>setBl({...bl,competitorId:e.target.value})}><option value="">Select competitor</option>{competitors.map(c=><option key={c.id} value={c.id}>{c.competitor_domain}</option>)}</select><input value={bl.source_url} onChange={e=>setBl({...bl,source_url:e.target.value})} placeholder="Source URL *"/><input value={bl.target_url} onChange={e=>setBl({...bl,target_url:e.target.value})} placeholder="Target URL"/><input value={bl.anchor_text} onChange={e=>setBl({...bl,anchor_text:e.target.value})} placeholder="Anchor"/><input type="number" min="0" max="100" step="0.1" value={bl.domain_authority} onChange={e=>setBl({...bl,domain_authority:e.target.value})} placeholder="Authority"/><select value={bl.status} onChange={e=>setBl({...bl,status:e.target.value})}><option value="active">Active</option><option value="lost">Lost</option><option value="new">New</option></select><button className="primary" disabled={saving}>Save</button></form></section><section className="panel"><div className="panel-title"><div><small>BACKLINK INVENTORY</small><h2>Competitor backlinks</h2></div><input className="compact-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..."/></div>{filteredBl.length?<div className="table-wrap"><table><thead><tr><th>Competitor</th><th>Source</th><th>Target</th><th>Anchor</th><th>Authority</th><th>Status</th><th>Source</th><th>Action</th></tr></thead><tbody>{filteredBl.map(x=><tr key={x.id}><td>{x.competitor_domain}</td><td>{x.source_url}</td><td>{x.target_url||'—'}</td><td>{x.anchor_text||'—'}</td><td>{x.domain_authority==null?'—':Number(x.domain_authority).toFixed(1)}</td><td>{x.status}</td><td>{x.source||'manual'}</td><td><button className="danger-link" onClick={async()=>{if(confirm('Delete this backlink observation?')){try{await deleteCompetitorBacklink(x.competitor_id,x.id);await load()}catch(e){setError(e.response?.data?.message||e.message)}}}}>Delete</button></td></tr>)}</tbody></table></div>:<div className="empty-state">No competitor backlinks.</div>}</section></>}
 {tab==='tools'&&<section className="panel free-tools-detail"><div className="panel-title"><div><small>STEP-BY-STEP TESTING</small><h2>How to test competitor intelligence</h2><span>You can test the complete intelligence engine without connecting a paid SEO data provider.</span></div></div><div className="free-tool-grid"><article className="free-tool-card"><div className="free-tool-icon">⌕</div><div><small>KEYWORD RANKING</small><h3>OnlineRankChecker</h3><p>Check a domain's Google position for up to 10 keywords at a time and choose the target country. No account required.</p><a className="primary tool-link" href="https://onlinerankchecker.com/" target="_blank" rel="noreferrer">Open free rank checker ↗</a></div></article><article className="free-tool-card"><div className="free-tool-icon">↗</div><div><small>BACKLINK RESEARCH</small><h3>Backlink Checker</h3><p>Check a competitor domain for backlink sources and review source URL, destination URL, anchor text, authority and spam-related metrics.</p><a className="primary tool-link" href="https://backlinkchecker.io/" target="_blank" rel="noreferrer">Open free backlink checker ↗</a></div></article></div><div className="research-guide"><div><b>1</b><h3>Choose a competitor</h3><p>Add a competitor domain above, for example <code>udemy.com</code>.</p></div><div><b>2</b><h3>Check keyword rankings</h3><p>Open OnlineRankChecker, enter the competitor domain and up to 10 target keywords. Record the keyword, position, search volume if available, and ranking URL.</p></div><div><b>3</b><h3>Check backlinks</h3><p>Open Backlink Checker, enter the competitor domain and identify useful referring pages/domains. Record source URL, target URL, anchor and authority.</p></div><div><b>4</b><h3>Enter observations</h3><p>Use the <b>Competitor Keywords</b> and <b>Competitor Backlinks</b> tabs to save the observations.</p></div><div><b>5</b><h3>Test the intelligence</h3><p>Return to Overview. RKVeda compares competitor observations with your tracked keywords/backlinks and surfaces gaps and opportunities.</p></div></div><div className="free-tool-disclaimer">Free external tools are third-party services. Their datasets, limits and accuracy can change. RKVeda stores only the observations you choose to enter; it does not scrape or automate these services.</div></section>}

 {tab==='opportunities'&&<><section className="panel"><div className="panel-title"><div><small>OPPORTUNITY PIPELINE</small><h2>Add backlink opportunity</h2></div></div><form className="intel-form" onSubmit={async e=>{e.preventDefault();await saveOpp({...opp,authority:opp.authority===''?null:Number(opp.authority)});setOpp({...opp,referring_domain:'',source_url:'',anchor_text:'',authority:'',notes:''})}}><input required value={opp.referring_domain} onChange={e=>setOpp({...opp,referring_domain:e.target.value})} placeholder="Referring domain *"/><input value={opp.source_url} onChange={e=>setOpp({...opp,source_url:e.target.value})} placeholder="Source URL"/><input value={opp.target_url} onChange={e=>setOpp({...opp,target_url:e.target.value})} placeholder="Target URL"/><input value={opp.anchor_text} onChange={e=>setOpp({...opp,anchor_text:e.target.value})} placeholder="Suggested anchor"/><input type="number" min="0" max="100" step="0.1" value={opp.authority} onChange={e=>setOpp({...opp,authority:e.target.value})} placeholder="Authority"/><select value={opp.priority} onChange={e=>setOpp({...opp,priority:e.target.value})}><option>low</option><option>medium</option><option>high</option><option>critical</option></select><button className="primary">Save opportunity</button></form></section><section className="panel"><div className="panel-title"><div><small>LINK BUILDING QUEUE</small><h2>Backlink opportunities</h2></div></div>{opportunities.length?<div className="table-wrap"><table><thead><tr><th>Domain</th><th>Source</th><th>Authority</th><th>Type</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{opportunities.map((o,i)=><tr key={`${o.referring_domain}-${o.id||i}`}><td><b>{o.referring_domain}</b></td><td>{o.source_url||'—'}</td><td>{o.authority==null?'—':Number(o.authority).toFixed(1)}</td><td>{o.opportunity_type}</td><td>{o.priority}</td><td>{o.status}</td><td>{o.id&&<><select className="inline-status" value={o.status} onChange={async e=>{try{await updateBacklinkOpportunity(projectId,o.id,{...o,status:e.target.value});await load()}catch(err){setError(err.response?.data?.message||err.message)}}}><option value="open">Open</option><option value="contacted">Contacted</option><option value="won">Won</option><option value="rejected">Rejected</option></select><button className="danger-link" onClick={async()=>{if(confirm('Delete this saved opportunity?')){try{await deleteBacklinkOpportunity(projectId,o.id);await load()}catch(err){setError(err.response?.data?.message||err.message)}}}}>Delete</button></>}</td></tr>)}</tbody></table></div>:<div className="empty-state">No opportunities.</div>}</section></>}
 </Layout>
}
