import {useCallback,useEffect,useMemo,useState} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import Layout from '../components/Layout';import Loading from '../components/Loading';
import {connectGbp,disconnectGbp,getGbpStatus,getGbpAccounts,getGbpLocations,selectGbpLocation,getGbpReport,syncGbp} from '../api/gbpApi';
const n=v=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(Number(v||0));
const pct=v=>`${Number(v||0).toFixed(1)}%`;
function dates(days=30){const end=new Date();end.setDate(end.getDate()-1);const start=new Date(end);start.setDate(start.getDate()-(days-1));const f=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return{startDate:f(start),endDate:f(end)}}
function metric(rows,name){return Number(rows?.find(x=>x.metric===name)?.value||0)}
export default function GoogleBusinessProfile(){const{projectId}=useParams();const[params]=useSearchParams();const[status,setStatus]=useState(null),[locations,setLocations]=useState([]),[report,setReport]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[range,setRange]=useState(30);
 const d=useMemo(()=>dates(range),[range]);
 const load=useCallback(async()=>{try{setLoading(true);setError('');const s=await getGbpStatus(projectId);setStatus(s);if(s.connected&&s.connection?.account_id){const l=await getGbpLocations(projectId);setLocations(l.locations||[]);if(s.connection.location_id){setReport(await getGbpReport(projectId,d));}}}catch(e){setError(e.response?.data?.message||e.message||'Unable to load GBP intelligence')}finally{setLoading(false)}},[projectId,d]);
 useEffect(()=>{if(projectId)load()},[projectId]);
 async function connect(){try{setBusy(true);const r=await connectGbp(projectId);window.location.href=r.authorizationUrl}catch(e){setError(e.response?.data?.message||e.message);setBusy(false)}}
 async function disconnect(){if(!window.confirm('Disconnect Google Business Profile for this project?'))return;try{setError('');await disconnectGbp(projectId);setStatus({connected:false,connection:null});setLocations([]);setReport(null);}catch(e){setError(e.response?.data?.message||e.message||'Unable to disconnect GBP')}}
 async function reconnect(){try{setBusy(true);setError('');await disconnectGbp(projectId);const r=await connectGbp(projectId);window.location.href=r.authorizationUrl}catch(e){setError(e.response?.data?.message||e.message||'Unable to reconnect GBP');setBusy(false)}}
 async function choose(e){const id=e.target.value;const l=locations.find(x=>x.locationId===id);if(!l)return;try{setBusy(true);await selectGbpLocation(projectId,{locationId:l.locationId,title:l.title});await load()}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
 async function sync(){try{setBusy(true);await syncGbp(projectId,d);await load()}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
 if(loading)return <Layout><Loading text="Loading Google Business Profile intelligence..."/></Layout>;
 const rows=report?.metrics||[],reviews=report?.reviews||{};const views=metric(rows,'BUSINESS_IMPRESSIONS_DESKTOP_MAPS')+metric(rows,'BUSINESS_IMPRESSIONS_DESKTOP_SEARCH')+metric(rows,'BUSINESS_IMPRESSIONS_MOBILE_MAPS')+metric(rows,'BUSINESS_IMPRESSIONS_MOBILE_SEARCH');
 return <Layout><header className="page-header"><div><small>LOCAL SEO INTELLIGENCE</small><h1>Google Business Profile</h1><p>Google Search + Maps visibility, actions and review health</p></div><div className="header-actions"><Link className="secondary" to={`/projects/${projectId}/seo`}>← SEO Command Center</Link><Link className="secondary" to={`/projects/${projectId}/ga4`}>GA4</Link></div></header>
 {params.get('gbp_error')&&<div className="alert">{params.get('gbp_error')}</div>}{error&&<div className="alert">{error}</div>}
 <section className="panel"><div className="panel-title"><div><small>GOOGLE BUSINESS PROFILE</small><h2>Connection</h2><span>Connect the Google account that owns or manages the Business Profile.</span></div><span className={`status-pill ${status?.connected?'success':''}`}>{status?.connected?'Connected':'Not connected'}</span></div>{!status?.connected?<div className="connect-empty"><p>GBP API access requires an approved Google Business Profile API project and OAuth consent. Google requires OAuth for Business Profile API requests. citeturn0search1turn0search3</p><button className="primary" onClick={connect} disabled={busy}>{busy?'Opening Google...':'Connect Google Business Profile'}</button></div>:<div className="gbp-connection-row"><div><b>{status.connection?.location_name||'Account connected'}</b><span>Account: {status.connection?.account_id||'—'} · Last sync: {status.connection?.last_synced_at||'Not synced'}</span></div><div className="gbp-actions"><select value={status.connection?.location_id||''} onChange={choose}><option value="">Select location</option>{locations.map(x=><option key={x.locationId} value={x.locationId}>{x.title||x.locationId}</option>)}</select><button className="primary" onClick={sync} disabled={busy||!status.connection?.location_id}>{busy?'Syncing...':'Sync now'}</button><button className="secondary" onClick={reconnect} disabled={busy}>{busy?'Reconnecting...':'↻ Reconnect'}</button><button className="danger-link" onClick={disconnect}>Disconnect</button></div></div>}</section>
 {status?.connected&&status.connection?.location_id&&<><div className="keyword-controls gbp-toolbar"><label>Period <select value={range} onChange={e=>setRange(Number(e.target.value))}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></label></div><section className="stats gbp-stats"><div className="stat-card"><small>Profile views</small><strong>{n(views)}</strong><span>Search + Maps</span></div><div className="stat-card"><small>Website clicks</small><strong>{n(metric(rows,'WEBSITE_CLICKS'))}</strong><span>From profile</span></div><div className="stat-card"><small>Phone clicks</small><strong>{n(metric(rows,'CALL_CLICKS'))}</strong><span>Customer actions</span></div><div className="stat-card"><small>Directions</small><strong>{n(metric(rows,'BUSINESS_DIRECTION_REQUESTS'))}</strong><span>Driving requests</span></div><div className="stat-card"><small>Reviews</small><strong>{n(reviews.review_count)}</strong><span>{Number(reviews.avg_rating||0).toFixed(1)} / 5 average</span></div></section>
 <div className="grid"><section className="panel"><div className="panel-title"><div><small>PROFILE HEALTH</small><h2>Location snapshot</h2></div></div>{report?.location?<div className="summary"><div><span>Business</span><b>{report.location.title||'—'}</b></div><div><span>Website</span><b>{report.location.website_uri||'—'}</b></div><div><span>Phone</span><b>{report.location.phone||'—'}</b></div><div><span>Category</span><b>{report.location.category||'—'}</b></div><div><span>Status</span><b>{report.location.status||'—'}</b></div></div>:<p className="muted">Sync the selected location to load its profile.</p>}</section><section className="panel"><div className="panel-title"><div><small>REVIEW HEALTH</small><h2>Review performance</h2></div></div><div className="metrics"><div><b>{Number(reviews.avg_rating||0).toFixed(1)}</b><span>Average rating</span></div><div><b>{n(reviews.review_count)}</b><span>Total synced</span></div><div><b>{n(reviews.replied_count)}</b><span>Replies</span></div></div><p className="muted">Recent reviews are stored project-wise so review health can be monitored over time.</p></section></div>
 <section className="panel"><div className="panel-title"><div><small>RECENT REVIEWS</small><h2>Customer feedback</h2></div><span>{n((reviews.recent||[]).length)} shown</span></div>{!(reviews.recent||[]).length?<div className="empty-state">No reviews synced yet. The selected location must be eligible for the Reviews API.</div>:<div className="table-wrap"><table><thead><tr><th>Rating</th><th>Reviewer</th><th>Comment</th><th>Replied</th><th>Updated</th></tr></thead><tbody>{reviews.recent.map(r=><tr key={r.review_id}><td><b>{r.star_rating||'—'}</b></td><td>{r.reviewer_name||'Google user'}</td><td className="wrap-cell">{r.comment||'—'}</td><td>{r.has_reply?'Yes':'No'}</td><td>{r.update_time||'—'}</td></tr>)}</tbody></table></div>}</section></>}
 <section className="panel"><div className="panel-title"><div><small>WHAT RKVEDA ANALYZES</small><h2>Local SEO intelligence</h2></div></div><div className="module-grid"><div><b>Search visibility</b><span>Search/Maps profile views</span></div><div><b>Customer actions</b><span>Website, calls and directions</span></div><div><b>Review health</b><span>Rating, volume and replies</span></div><div><b>Profile health</b><span>Website, phone, category and status</span></div></div></section>
 </Layout>}
