import {useEffect,useState} from 'react';
import {Link,useParams,useSearchParams} from'react-router-dom';
import Layout from'../components/Layout';import Loading from'../components/Loading';
import{getSocialIntelligence,connectSocial,syncSocial,disconnectSocial}from'../api/socialIntelligenceApi';
const n=v=>new Intl.NumberFormat('en-IN').format(Number(v||0));
const labels={facebook:'Facebook',instagram:'Instagram',linkedin:'LinkedIn',youtube:'YouTube',x:'X',tiktok:'TikTok',other:'Other'};
export default function SocialMediaIntelligence(){const{projectId}=useParams();const[params]=useSearchParams();const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[platform,setPlatform]=useState('instagram');
 async function load(){try{setLoading(true);setError('');setData(await getSocialIntelligence(projectId))}catch(e){setError(e.response?.data?.message||e.message||'Unable to load social intelligence')}finally{setLoading(false)}}
 useEffect(()=>{load()},[projectId]);
 useEffect(()=>{const e=params.get('social_error');if(e)setError(e)},[params]);
 const connections=data?.connections||[];const profiles=data?.profiles||[];const metrics=data?.metrics||[];const totals=data?.totals||{};const active=metrics.find(x=>x.platform===platform);const conn=connections.find(x=>x.platform===platform);const profile=profiles.find(x=>x.platform===platform);const provider=data?.providers?.[platform];
 async function connect(){try{setBusy(true);setError('');const r=await connectSocial(projectId,platform);window.location.href=r.authorizationUrl}catch(e){setError(e.response?.data?.message||e.message||'Unable to connect provider');setBusy(false)}}
 async function sync(){try{setBusy(true);setError('');await syncSocial(projectId,platform);await load()}catch(e){setError(e.response?.data?.message||e.message||'Unable to sync provider')}finally{setBusy(false)}}
 async function disconnect(){if(!confirm(`Disconnect ${labels[platform]}?`))return;try{setBusy(true);await disconnectSocial(projectId,platform);await load()}catch(e){setError(e.response?.data?.message||e.message)}finally{setBusy(false)}}
 if(loading)return <Layout><Loading text="Loading social media intelligence..."/></Layout>;
 return <Layout><header className="page-header"><div><small>SOCIAL INTELLIGENCE</small><h1>Social Media Intelligence</h1><p>Connect official platform APIs and keep audience, engagement and content data synchronized automatically.</p></div><div className="header-actions"><Link className="secondary" to={`/projects/${projectId}/seo`}>← SEO Command Center</Link><Link className="secondary" to={`/projects/${projectId}/gbp`}>GBP</Link><Link className="secondary" to={`/projects/${projectId}/social-api-guide`}>API Setup Guide</Link></div></header>
 {params.get('social_connected')&&<div className="social-sync-success">{labels[params.get('social_connected')]||'Social'} connected and initial sync completed.</div>}{error&&<div className="alert">{error}</div>}
 <section className="stats social-stats"><div className="stat-card"><small>Platforms connected</small><strong>{n(connections.filter(x=>x.status==='connected').length)}</strong><span>Official API connections</span></div><div className="stat-card"><small>Reach</small><strong>{n(totals.reach)}</strong><span>Last 30 days</span></div><div className="stat-card"><small>Engagement</small><strong>{n(totals.likes+totals.comments+totals.shares)}</strong><span>Likes + comments + shares</span></div><div className="stat-card"><small>Video views</small><strong>{n(totals.video_views)}</strong><span>Last 30 days</span></div></section>
 <section className="panel"><div className="panel-title"><div><small>PLATFORM</small><h2>Choose channel</h2></div></div><div className="social-platforms">{Object.entries(labels).map(([k,v])=><button key={k} className={platform===k?'active':''} onClick={()=>setPlatform(k)}>{v}{connections.some(x=>x.platform===k&&x.status==='connected')?' ✓':''}</button>)}</div></section>
 <section className="panel social-connection-panel"><div className="panel-title"><div><small>OFFICIAL API CONNECTION</small><h2>{labels[platform]}</h2><span>{provider?.configured?'Provider credentials are configured.':'Provider credentials are not configured yet.'}</span></div><span className={`status-pill ${conn?.status==='connected'?'success':''}`}>{conn?.status==='connected'?'Connected':'Not connected'}</span></div>
 {!conn?<div className="connect-empty"><p>{platform==='instagram'||platform==='facebook'?'Meta OAuth connects the selected professional Facebook/Instagram account. Instagram requires a professional account linked to a managed Facebook Page.':platform==='youtube'?'Google OAuth connects the YouTube channel owned or managed by the authorized Google account.':`${labels[platform]} requires its own developer app, OAuth credentials and any provider-specific API approval.`}</p>{!provider?.configured || !provider?.enabled
  ? <Link className="primary" to={`/projects/${projectId}/social-api-guide`}>{!provider?.enabled ? 'Open API setup guide' : 'Configure API first'}</Link>
  : <button className="primary" onClick={connect} disabled={busy}>{busy?'Opening provider...':'Connect API'}</button>}</div>:<div className="gbp-connection-row"><div><b>{conn.account_name||profile?.handle||labels[platform]}</b><span>Account: {conn.account_id||'—'} · Last sync: {conn.last_synced_at||'Not synced'}</span></div><div className="gbp-actions"><button className="primary" onClick={sync} disabled={busy}>{busy?'Syncing...':'Sync now'}</button><button className="secondary" onClick={connect} disabled={busy}>↻ Reconnect</button><button className="danger-link" onClick={disconnect} disabled={busy}>Disconnect</button></div></div>}</section>
 <div className="grid"><section className="panel"><div className="panel-title"><div><small>PROFILE</small><h2>{labels[platform]} profile</h2></div><span>{conn?'API synced':'Waiting for API'}</span></div>{profile?<div className="summary"><div><span>Handle / channel</span><b>{profile.handle||'—'}</b></div><div><span>Followers / subscribers</span><b>{n(profile.followers)}</b></div><div><span>Following</span><b>{n(profile.following)}</b></div><div><span>Posts / videos</span><b>{n(profile.posts_count)}</b></div><div><span>Profile</span><b className="wrap-cell">{profile.profile_url||'—'}</b></div></div>:<p className="muted">Connect an official API to populate this profile automatically.</p>}</section><section className="panel"><div className="panel-title"><div><small>CURRENT 30-DAY SNAPSHOT</small><h2>{labels[platform]}</h2></div></div>{active?<div className="metrics"><div><b>{n(active.followers)}</b><span>Followers</span></div><div><b>{n(active.reach)}</b><span>Reach / views</span></div><div><b>{Number(active.engagement_rate||0).toFixed(2)}%</b><span>Engagement rate</span></div></div>:<p className="muted">Sync the connected account to populate the snapshot.</p>}</section></div>
 <section className="panel"><div className="panel-title"><div><small>RECENT CONTENT</small><h2>Posts & videos</h2></div><span>{n((data?.posts||[]).length)} tracked</span></div>{!(data?.posts||[]).length?<div className="empty-state">No API content has been synchronized for this platform yet.</div>:<div className="table-wrap"><table><thead><tr><th>Platform</th><th>Published</th><th>Content</th><th>Likes</th><th>Comments</th><th>Shares</th><th>Views</th><th>Source</th></tr></thead><tbody>{data.posts.map(x=><tr key={x.id}><td>{labels[x.platform]}</td><td>{x.published_at||'—'}</td><td className="wrap-cell">{x.caption||x.post_url||'—'}</td><td>{n(x.likes)}</td><td>{n(x.comments)}</td><td>{n(x.shares)}</td><td>{n(x.views)}</td><td>{x.source||'api'}</td></tr>)}</tbody></table></div>}</section>
 <section className="panel"><div className="panel-title"><div><small>AUTOMATION MODEL</small><h2>No more manual daily entry</h2></div></div><div className="module-grid"><div><b>OAuth connection</b><span>Account access is authorized by the platform owner.</span></div><div><b>Scheduled sync ready</b><span>Use the same sync endpoint from a daily worker/cron.</span></div><div><b>API source tracking</b><span>Imported content is marked as API data.</span></div><div><b>Project isolation</b><span>Every connection and sync is scoped to the RKVeda project.</span></div><div><b>Provider limits</b><span>Metrics depend on the permissions and API products approved for each platform.</span></div></div></section>
 </Layout>}
